[[redirects]]
  from = "/api/*"
  to = "http://18.141.211.167:3000/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/socket.io/*"
  to = "http://18.141.211.167:3000/socket.io/:splat"
  status = 200
  force = true
